CXXFLAGS            = -O2 -flto -fno-fat-lto-objects -fPIC -Wall -Wextra
LIBTOKAMAK_CXXFLAGS = $(CXXFLAGS) -Wno-unknown-pragmas -Wno-unused-variable  -Wno-unused-but-set-variable -Wno-switch -Wno-strict-aliasing -Wno-class-memaccess
LFLAGS              = -Wl,-O1 -pipe -O2 -flto=6 -fno-fat-lto-objects -fuse-linker-plugin -fPIC
CXX                 = g++
LINK                = g++
LIBTOKAMAK_OBJS     = boxcylinder.o collisionbody.o collision.o constraint.o cylinder.o dcd.o lines.o ne_interface.o perflinux.o region.o restcontact.o rigidbodybase.o rigidbody.o scenery.o simulator.o solver.o sphere.o stack.o tricollision.o
LIBTOKAMAK_TARGET   = libtokamak.a
GLAPP_OBJ           = tok_sample_glapp.o
GLAPP_TARGETS       = balljoints breakageobjects car hingejointmotoron hingejoints raddude rigidparticlesandterrain sccollision stackingobjects tank

.PHONY: all clean

all: $(GLAPP_TARGETS)

clean:
	rm -f $(LIBTOKAMAK_TARGET) *.o $(GLAPP_TARGETS)

$(LIBTOKAMAK_TARGET): $(LIBTOKAMAK_OBJS)
	ar rcs $(LIBTOKAMAK_TARGET) $(LIBTOKAMAK_OBJS)
	ranlib $(LIBTOKAMAK_TARGET)

$(LIBTOKAMAK_OBJS): %.o: ../tokamaksrc/src/%.cpp ../tokamaksrc/src/*.h ../include/*.h ../include/math/*.h
	$(CXX) $(LIBTOKAMAK_CXXFLAGS) -c -I../include $< -o $@

$(GLAPP_OBJ): %.o: %.cpp *.h ../include/*.h ../include/math/*.h
	$(CXX) $(CXXFLAGS) -c -I../include $< -o $@

%.o: %.cpp *.h ../include/*.h ../include/math/*.h
	$(CXX) $(CXXFLAGS) -c -I../include $< -o $@

$(GLAPP_TARGETS): %: %.o $(LIBTOKAMAK_TARGET) $(GLAPP_OBJ)
	$(CXX) $(LFLAGS) -o $@ $< $(GLAPP_OBJ) -L./ -lSDL2 -lGL $(LIBTOKAMAK_TARGET)
